/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type QuittanceStruct = {
  paymentId: BytesLike;
  requestHash: BytesLike;
  resultHash: BytesLike;
  sellerPassport: AddressLike;
  buyerPassport: AddressLike;
  proofType: BigNumberish;
  proofPayload: BytesLike;
  attestor: AddressLike;
  deliveredAt: BigNumberish;
  deadline: BigNumberish;
};

export type QuittanceStructOutput = [
  paymentId: string,
  requestHash: string,
  resultHash: string,
  sellerPassport: string,
  buyerPassport: string,
  proofType: bigint,
  proofPayload: string,
  attestor: string,
  deliveredAt: bigint,
  deadline: bigint
] & {
  paymentId: string;
  requestHash: string;
  resultHash: string;
  sellerPassport: string;
  buyerPassport: string;
  proofType: bigint;
  proofPayload: string;
  attestor: string;
  deliveredAt: bigint;
  deadline: bigint;
};

export interface AdapterRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adapters"
      | "owner"
      | "register"
      | "remove"
      | "renounceOwnership"
      | "transferOwnership"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterRegistered"
      | "AdapterRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adapters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [QuittanceStruct]
  ): string;

  decodeFunctionResult(functionFragment: "adapters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AdapterRegisteredEvent {
  export type InputTuple = [proofType: BigNumberish, adapter: AddressLike];
  export type OutputTuple = [proofType: bigint, adapter: string];
  export interface OutputObject {
    proofType: bigint;
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdapterRemovedEvent {
  export type InputTuple = [proofType: BigNumberish];
  export type OutputTuple = [proofType: bigint];
  export interface OutputObject {
    proofType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AdapterRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AdapterRegistry;
  waitForDeployment(): Promise<this>;

  interface: AdapterRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adapters: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<
    [proofType: BigNumberish, adapter: AddressLike],
    [void],
    "nonpayable"
  >;

  remove: TypedContractMethod<[proofType: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<[q: QuittanceStruct], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adapters"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [proofType: BigNumberish, adapter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove"
  ): TypedContractMethod<[proofType: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[q: QuittanceStruct], [boolean], "view">;

  getEvent(
    key: "AdapterRegistered"
  ): TypedContractEvent<
    AdapterRegisteredEvent.InputTuple,
    AdapterRegisteredEvent.OutputTuple,
    AdapterRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AdapterRemoved"
  ): TypedContractEvent<
    AdapterRemovedEvent.InputTuple,
    AdapterRemovedEvent.OutputTuple,
    AdapterRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AdapterRegistered(uint8,address)": TypedContractEvent<
      AdapterRegisteredEvent.InputTuple,
      AdapterRegisteredEvent.OutputTuple,
      AdapterRegisteredEvent.OutputObject
    >;
    AdapterRegistered: TypedContractEvent<
      AdapterRegisteredEvent.InputTuple,
      AdapterRegisteredEvent.OutputTuple,
      AdapterRegisteredEvent.OutputObject
    >;

    "AdapterRemoved(uint8)": TypedContractEvent<
      AdapterRemovedEvent.InputTuple,
      AdapterRemovedEvent.OutputTuple,
      AdapterRemovedEvent.OutputObject
    >;
    AdapterRemoved: TypedContractEvent<
      AdapterRemovedEvent.InputTuple,
      AdapterRemovedEvent.OutputTuple,
      AdapterRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
