/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BondInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN"
      | "MIN_BOND"
      | "bonds"
      | "consumeGasFloat"
      | "deposit"
      | "escrow"
      | "gasFloat"
      | "isSufficientlyBonded"
      | "minBondRequired"
      | "owner"
      | "renounceOwnership"
      | "requestWithdraw"
      | "setEscrow"
      | "slash"
      | "token"
      | "topUpGasFloat"
      | "totalSlashed"
      | "transferOwnership"
      | "withdraw"
      | "withdrawRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "EscrowSet"
      | "GasFloatConsumed"
      | "GasFloatToppedUp"
      | "OwnershipTransferred"
      | "Slashed"
      | "WithdrawRequested"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "COOLDOWN", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_BOND", values?: undefined): string;
  encodeFunctionData(functionFragment: "bonds", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "consumeGasFloat",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gasFloat",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSufficientlyBonded",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minBondRequired",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "topUpGasFloat",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSlashed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawRequests",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "COOLDOWN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_BOND", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bonds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "consumeGasFloat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasFloat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSufficientlyBonded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minBondRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "topUpGasFloat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSlashed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRequests",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [seller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [seller: string, amount: bigint];
  export interface OutputObject {
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowSetEvent {
  export type InputTuple = [escrow: AddressLike];
  export type OutputTuple = [escrow: string];
  export interface OutputObject {
    escrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasFloatConsumedEvent {
  export type InputTuple = [seller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [seller: string, amount: bigint];
  export interface OutputObject {
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasFloatToppedUpEvent {
  export type InputTuple = [seller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [seller: string, amount: bigint];
  export interface OutputObject {
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashedEvent {
  export type InputTuple = [
    seller: AddressLike,
    requested: BigNumberish,
    actual: BigNumberish
  ];
  export type OutputTuple = [seller: string, requested: bigint, actual: bigint];
  export interface OutputObject {
    seller: string;
    requested: bigint;
    actual: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawRequestedEvent {
  export type InputTuple = [
    seller: AddressLike,
    amount: BigNumberish,
    availableAt: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    amount: bigint,
    availableAt: bigint
  ];
  export interface OutputObject {
    seller: string;
    amount: bigint;
    availableAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [seller: AddressLike, amount: BigNumberish];
  export type OutputTuple = [seller: string, amount: bigint];
  export interface OutputObject {
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Bond extends BaseContract {
  connect(runner?: ContractRunner | null): Bond;
  waitForDeployment(): Promise<this>;

  interface: BondInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MIN_BOND: TypedContractMethod<[], [bigint], "view">;

  bonds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  consumeGasFloat: TypedContractMethod<
    [seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  escrow: TypedContractMethod<[], [string], "view">;

  gasFloat: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  isSufficientlyBonded: TypedContractMethod<
    [seller: AddressLike, price: BigNumberish],
    [boolean],
    "view"
  >;

  minBondRequired: TypedContractMethod<
    [price: BigNumberish, multiplier: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEscrow: TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;

  slash: TypedContractMethod<
    [seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  topUpGasFloat: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalSlashed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawRequests: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; availableAt: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bonds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "consumeGasFloat"
  ): TypedContractMethod<
    [seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gasFloat"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isSufficientlyBonded"
  ): TypedContractMethod<
    [seller: AddressLike, price: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "minBondRequired"
  ): TypedContractMethod<
    [price: BigNumberish, multiplier: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrow"
  ): TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "topUpGasFloat"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalSlashed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRequests"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; availableAt: bigint }],
    "view"
  >;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowSet"
  ): TypedContractEvent<
    EscrowSetEvent.InputTuple,
    EscrowSetEvent.OutputTuple,
    EscrowSetEvent.OutputObject
  >;
  getEvent(
    key: "GasFloatConsumed"
  ): TypedContractEvent<
    GasFloatConsumedEvent.InputTuple,
    GasFloatConsumedEvent.OutputTuple,
    GasFloatConsumedEvent.OutputObject
  >;
  getEvent(
    key: "GasFloatToppedUp"
  ): TypedContractEvent<
    GasFloatToppedUpEvent.InputTuple,
    GasFloatToppedUpEvent.OutputTuple,
    GasFloatToppedUpEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Slashed"
  ): TypedContractEvent<
    SlashedEvent.InputTuple,
    SlashedEvent.OutputTuple,
    SlashedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawRequested"
  ): TypedContractEvent<
    WithdrawRequestedEvent.InputTuple,
    WithdrawRequestedEvent.OutputTuple,
    WithdrawRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "EscrowSet(address)": TypedContractEvent<
      EscrowSetEvent.InputTuple,
      EscrowSetEvent.OutputTuple,
      EscrowSetEvent.OutputObject
    >;
    EscrowSet: TypedContractEvent<
      EscrowSetEvent.InputTuple,
      EscrowSetEvent.OutputTuple,
      EscrowSetEvent.OutputObject
    >;

    "GasFloatConsumed(address,uint256)": TypedContractEvent<
      GasFloatConsumedEvent.InputTuple,
      GasFloatConsumedEvent.OutputTuple,
      GasFloatConsumedEvent.OutputObject
    >;
    GasFloatConsumed: TypedContractEvent<
      GasFloatConsumedEvent.InputTuple,
      GasFloatConsumedEvent.OutputTuple,
      GasFloatConsumedEvent.OutputObject
    >;

    "GasFloatToppedUp(address,uint256)": TypedContractEvent<
      GasFloatToppedUpEvent.InputTuple,
      GasFloatToppedUpEvent.OutputTuple,
      GasFloatToppedUpEvent.OutputObject
    >;
    GasFloatToppedUp: TypedContractEvent<
      GasFloatToppedUpEvent.InputTuple,
      GasFloatToppedUpEvent.OutputTuple,
      GasFloatToppedUpEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Slashed(address,uint256,uint256)": TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;
    Slashed: TypedContractEvent<
      SlashedEvent.InputTuple,
      SlashedEvent.OutputTuple,
      SlashedEvent.OutputObject
    >;

    "WithdrawRequested(address,uint256,uint64)": TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;
    WithdrawRequested: TypedContractEvent<
      WithdrawRequestedEvent.InputTuple,
      WithdrawRequestedEvent.OutputTuple,
      WithdrawRequestedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
