/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bond"
      | "escrows"
      | "failedCount"
      | "getEscrowRecord"
      | "openEscrow"
      | "owner"
      | "refund"
      | "registry"
      | "renounceOwnership"
      | "setRegistry"
      | "settle"
      | "token"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowOpened"
      | "EscrowRefunded"
      | "EscrowSettled"
      | "OwnershipTransferred"
      | "RegistrySet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bond", values?: undefined): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "failedCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openEscrow",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "settle", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "failedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace EscrowOpenedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    proofType: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    buyer: string,
    seller: string,
    amount: bigint,
    deadline: bigint,
    proofType: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    buyer: string;
    seller: string;
    amount: bigint;
    deadline: bigint;
    proofType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    buyer: AddressLike,
    amount: BigNumberish,
    slashed: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    buyer: string,
    amount: bigint,
    slashed: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    buyer: string;
    amount: bigint;
    slashed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowSettledEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [paymentId: string, seller: string, amount: bigint];
  export interface OutputObject {
    paymentId: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escrow extends BaseContract {
  connect(runner?: ContractRunner | null): Escrow;
  waitForDeployment(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bond: TypedContractMethod<[], [string], "view">;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean, boolean] & {
        buyer: string;
        seller: string;
        amount: bigint;
        deadline: bigint;
        proofType: bigint;
        settled: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  failedCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEscrowRecord: TypedContractMethod<
    [paymentId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        buyer: string;
        seller: string;
        amount: bigint;
        deadline: bigint;
        settled: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  openEscrow: TypedContractMethod<
    [
      paymentId: BytesLike,
      buyer: AddressLike,
      seller: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      proofType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean, boolean] & {
        buyer: string;
        seller: string;
        amount: bigint;
        deadline: bigint;
        proofType: bigint;
        settled: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "failedCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrowRecord"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        buyer: string;
        seller: string;
        amount: bigint;
        deadline: bigint;
        settled: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "openEscrow"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      buyer: AddressLike,
      seller: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      proofType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EscrowOpened"
  ): TypedContractEvent<
    EscrowOpenedEvent.InputTuple,
    EscrowOpenedEvent.OutputTuple,
    EscrowOpenedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowSettled"
  ): TypedContractEvent<
    EscrowSettledEvent.InputTuple,
    EscrowSettledEvent.OutputTuple,
    EscrowSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RegistrySet"
  ): TypedContractEvent<
    RegistrySetEvent.InputTuple,
    RegistrySetEvent.OutputTuple,
    RegistrySetEvent.OutputObject
  >;

  filters: {
    "EscrowOpened(bytes32,address,address,uint256,uint64,uint8)": TypedContractEvent<
      EscrowOpenedEvent.InputTuple,
      EscrowOpenedEvent.OutputTuple,
      EscrowOpenedEvent.OutputObject
    >;
    EscrowOpened: TypedContractEvent<
      EscrowOpenedEvent.InputTuple,
      EscrowOpenedEvent.OutputTuple,
      EscrowOpenedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,address,uint256,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowSettled(bytes32,address,uint256)": TypedContractEvent<
      EscrowSettledEvent.InputTuple,
      EscrowSettledEvent.OutputTuple,
      EscrowSettledEvent.OutputObject
    >;
    EscrowSettled: TypedContractEvent<
      EscrowSettledEvent.InputTuple,
      EscrowSettledEvent.OutputTuple,
      EscrowSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RegistrySet(address)": TypedContractEvent<
      RegistrySetEvent.InputTuple,
      RegistrySetEvent.OutputTuple,
      RegistrySetEvent.OutputObject
    >;
    RegistrySet: TypedContractEvent<
      RegistrySetEvent.InputTuple,
      RegistrySetEvent.OutputTuple,
      RegistrySetEvent.OutputObject
    >;
  };
}
