/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type QuittanceStruct = {
  paymentId: BytesLike;
  requestHash: BytesLike;
  resultHash: BytesLike;
  sellerPassport: AddressLike;
  buyerPassport: AddressLike;
  proofType: BigNumberish;
  proofPayload: BytesLike;
  attestor: AddressLike;
  deliveredAt: BigNumberish;
  deadline: BigNumberish;
};

export type QuittanceStructOutput = [
  paymentId: string,
  requestHash: string,
  resultHash: string,
  sellerPassport: string,
  buyerPassport: string,
  proofType: bigint,
  proofPayload: string,
  attestor: string,
  deliveredAt: bigint,
  deadline: bigint
] & {
  paymentId: string;
  requestHash: string;
  resultHash: string;
  sellerPassport: string;
  buyerPassport: string;
  proofType: bigint;
  proofPayload: string;
  attestor: string;
  deliveredAt: bigint;
  deadline: bigint;
};

export interface QuittanceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adapterRegistry"
      | "escrow"
      | "getQuittance"
      | "post"
      | "successCount"
      | "totalVolume"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "QuittancePosted"): EventFragment;

  encodeFunctionData(
    functionFragment: "adapterRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getQuittance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "post",
    values: [QuittanceStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "successCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "adapterRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getQuittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "post", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "successCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
}

export namespace QuittancePostedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    sellerPassport: AddressLike,
    buyerPassport: AddressLike,
    proofType: BigNumberish,
    resultHash: BytesLike
  ];
  export type OutputTuple = [
    paymentId: string,
    sellerPassport: string,
    buyerPassport: string,
    proofType: bigint,
    resultHash: string
  ];
  export interface OutputObject {
    paymentId: string;
    sellerPassport: string;
    buyerPassport: string;
    proofType: bigint;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuittanceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): QuittanceRegistry;
  waitForDeployment(): Promise<this>;

  interface: QuittanceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adapterRegistry: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  getQuittance: TypedContractMethod<
    [paymentId: BytesLike],
    [QuittanceStructOutput],
    "view"
  >;

  post: TypedContractMethod<[q: QuittanceStruct], [void], "nonpayable">;

  successCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalVolume: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adapterRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getQuittance"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [QuittanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "post"
  ): TypedContractMethod<[q: QuittanceStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "successCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "QuittancePosted"
  ): TypedContractEvent<
    QuittancePostedEvent.InputTuple,
    QuittancePostedEvent.OutputTuple,
    QuittancePostedEvent.OutputObject
  >;

  filters: {
    "QuittancePosted(bytes32,address,address,uint8,bytes32)": TypedContractEvent<
      QuittancePostedEvent.InputTuple,
      QuittancePostedEvent.OutputTuple,
      QuittancePostedEvent.OutputObject
    >;
    QuittancePosted: TypedContractEvent<
      QuittancePostedEvent.InputTuple,
      QuittancePostedEvent.OutputTuple,
      QuittancePostedEvent.OutputObject
    >;
  };
}
