/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReputationViewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIER_BRONZE"
      | "TIER_GOLD"
      | "TIER_SILVER"
      | "bond"
      | "bondBalance"
      | "escrow"
      | "registry"
      | "slashedTotal"
      | "successRate"
      | "summary"
      | "tier"
      | "volumeSettled"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "TIER_BRONZE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER_GOLD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER_SILVER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bond", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bondBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "slashedTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "successRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "summary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "tier", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "volumeSettled",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "TIER_BRONZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER_GOLD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIER_SILVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bondBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slashedTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "successRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "summary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "volumeSettled",
    data: BytesLike
  ): Result;
}

export interface ReputationView extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationView;
  waitForDeployment(): Promise<this>;

  interface: ReputationViewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIER_BRONZE: TypedContractMethod<[], [bigint], "view">;

  TIER_GOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_SILVER: TypedContractMethod<[], [bigint], "view">;

  bond: TypedContractMethod<[], [string], "view">;

  bondBalance: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  slashedTotal: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  successRate: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  summary: TypedContractMethod<
    [seller: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        successRateBps: bigint;
        settled: bigint;
        slashed: bigint;
        activeBond: bigint;
        sellerTier: bigint;
      }
    ],
    "view"
  >;

  tier: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  volumeSettled: TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIER_BRONZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_GOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_SILVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bondBalance"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "slashedTotal"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "successRate"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "summary"
  ): TypedContractMethod<
    [seller: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        successRateBps: bigint;
        settled: bigint;
        slashed: bigint;
        activeBond: bigint;
        sellerTier: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tier"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "volumeSettled"
  ): TypedContractMethod<[seller: AddressLike], [bigint], "view">;

  filters: {};
}
