/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProofAdapter,
  IProofAdapterInterface,
} from "../../../contracts/interfaces/IProofAdapter";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "paymentId",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "requestHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "resultHash",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "sellerPassport",
            type: "address",
          },
          {
            internalType: "address",
            name: "buyerPassport",
            type: "address",
          },
          {
            internalType: "enum ProofType",
            name: "proofType",
            type: "uint8",
          },
          {
            internalType: "bytes",
            name: "proofPayload",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "attestor",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "deliveredAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "deadline",
            type: "uint64",
          },
        ],
        internalType: "struct Quittance",
        name: "q",
        type: "tuple",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProofAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IProofAdapterInterface {
    return new Interface(_abi) as IProofAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProofAdapter {
    return new Contract(address, _abi, runner) as unknown as IProofAdapter;
  }
}
