/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OracleAdapter } from "./OracleAdapter";
export type { TimeoutAdapter } from "./TimeoutAdapter";
