/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type QuittanceStruct = {
  paymentId: BytesLike;
  requestHash: BytesLike;
  resultHash: BytesLike;
  sellerPassport: AddressLike;
  buyerPassport: AddressLike;
  proofType: BigNumberish;
  proofPayload: BytesLike;
  attestor: AddressLike;
  deliveredAt: BigNumberish;
  deadline: BigNumberish;
};

export type QuittanceStructOutput = [
  paymentId: string,
  requestHash: string,
  resultHash: string,
  sellerPassport: string,
  buyerPassport: string,
  proofType: bigint,
  proofPayload: string,
  attestor: string,
  deliveredAt: bigint,
  deadline: bigint
] & {
  paymentId: string;
  requestHash: string;
  resultHash: string;
  sellerPassport: string;
  buyerPassport: string;
  proofType: bigint;
  proofPayload: string;
  attestor: string;
  deliveredAt: bigint;
  deadline: bigint;
};

export interface OracleAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "owner"
      | "registerAttestor"
      | "registeredAttestors"
      | "renounceOwnership"
      | "revokeAttestor"
      | "transferOwnership"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestorRegistered"
      | "AttestorRevoked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAttestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredAttestors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAttestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [QuittanceStruct]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAttestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredAttestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAttestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AttestorRegisteredEvent {
  export type InputTuple = [attestor: AddressLike];
  export type OutputTuple = [attestor: string];
  export interface OutputObject {
    attestor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestorRevokedEvent {
  export type InputTuple = [attestor: AddressLike];
  export type OutputTuple = [attestor: string];
  export interface OutputObject {
    attestor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): OracleAdapter;
  waitForDeployment(): Promise<this>;

  interface: OracleAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  registerAttestor: TypedContractMethod<
    [attestor: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredAttestors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeAttestor: TypedContractMethod<
    [attestor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<[q: QuittanceStruct], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAttestor"
  ): TypedContractMethod<[attestor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredAttestors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAttestor"
  ): TypedContractMethod<[attestor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[q: QuittanceStruct], [boolean], "view">;

  getEvent(
    key: "AttestorRegistered"
  ): TypedContractEvent<
    AttestorRegisteredEvent.InputTuple,
    AttestorRegisteredEvent.OutputTuple,
    AttestorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AttestorRevoked"
  ): TypedContractEvent<
    AttestorRevokedEvent.InputTuple,
    AttestorRevokedEvent.OutputTuple,
    AttestorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AttestorRegistered(address)": TypedContractEvent<
      AttestorRegisteredEvent.InputTuple,
      AttestorRegisteredEvent.OutputTuple,
      AttestorRegisteredEvent.OutputObject
    >;
    AttestorRegistered: TypedContractEvent<
      AttestorRegisteredEvent.InputTuple,
      AttestorRegisteredEvent.OutputTuple,
      AttestorRegisteredEvent.OutputObject
    >;

    "AttestorRevoked(address)": TypedContractEvent<
      AttestorRevokedEvent.InputTuple,
      AttestorRevokedEvent.OutputTuple,
      AttestorRevokedEvent.OutputObject
    >;
    AttestorRevoked: TypedContractEvent<
      AttestorRevokedEvent.InputTuple,
      AttestorRevokedEvent.OutputTuple,
      AttestorRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
