/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type QuittanceStruct = {
  paymentId: BytesLike;
  requestHash: BytesLike;
  resultHash: BytesLike;
  sellerPassport: AddressLike;
  buyerPassport: AddressLike;
  proofType: BigNumberish;
  proofPayload: BytesLike;
  attestor: AddressLike;
  deliveredAt: BigNumberish;
  deadline: BigNumberish;
};

export type QuittanceStructOutput = [
  paymentId: string,
  requestHash: string,
  resultHash: string,
  sellerPassport: string,
  buyerPassport: string,
  proofType: bigint,
  proofPayload: string,
  attestor: string,
  deliveredAt: bigint,
  deadline: bigint
] & {
  paymentId: string;
  requestHash: string;
  resultHash: string;
  sellerPassport: string;
  buyerPassport: string;
  proofType: bigint;
  proofPayload: string;
  attestor: string;
  deliveredAt: bigint;
  deadline: bigint;
};

export interface IProofAdapterInterface extends Interface {
  getFunction(nameOrSignature: "verify"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verify",
    values: [QuittanceStruct]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface IProofAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): IProofAdapter;
  waitForDeployment(): Promise<this>;

  interface: IProofAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verify: TypedContractMethod<[q: QuittanceStruct], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[q: QuittanceStruct], [boolean], "view">;

  filters: {};
}
